# Site settings
title: Red Pitaya Notes
description: Notes on the Red Pitaya Open Source Instrument
baseurl: /red-pitaya-notes
url: http://pavel-demin.github.io

release-image: https://github.com/pavel-demin/red-pitaya-notes/releases/download/20220322/red-pitaya-alpine-3.14-armv7-20220322.zip
scanner-image: https://github.com/pavel-demin/red-pitaya-notes/releases/download/20220322/red-pitaya-alpine-3.14-armv7-20220322-scanner.zip

# Build settings
markdown: kramdown
highlighter: rouge
